#
#
#
# template environment variables
# DO NOT EDIT THIS FILE, copy to ./v-env.sh
# cp ./t-env.sh ./v-env.sh
#
#
#

export KUBE_PUB_ADDR="kube.example.com"

export CLUSTER_NAME="kubernetes-the-hard-way"
export CONTEXT_NAME="default"

export WORKER_LIST=(kube-worker-1 kube-worker-2 kube-worker-3)
export WORKER_INTERN_IP_LIST=(10.0.0.1 10.0.0.2 10.0.0.3)
export WORKER_EXTERN_IP_LIST=(10.0.0.1 10.0.0.2 10.0.0.3)

export CONTROLLER_LIST=(kube-controller)
export CONTROLLER_INTERN_IP_LIST=(10.0.0.10)
export CONTROLLER_EXTERN_IP_LIST=(10.0.0.10)

export KUBE_ETCD_CLUSTER_NAME="etcd-cluster-kube"
export KUBE_ETCD_LISTEN_CLIENT_PORT="2379"
export KUBE_ETCD_LISTEN_PEER_PORT="2380"

export KUBE_SERVICE_IP_RANGE="10.32.0.0/24"
export KUBE_SERVICE_PORT_RANGE="30000-32767"
export KUBE_CLUSTER_CIDR="10.200.0.0/16"
export KUBE_API_SERVER_PORT="6443"

export WORKER_ADDR_LIST=""
export ETCD_INITIAL_CLUSTERS=""

export GEN_DIR="generated"

export CERT_ORG_UNIT="Kubernetes The Hard Way"
export CERT_COUNTRY="US"
export CERT_LOCATION="Portland"
export CERT_STATE="Oregon"

# 
# 
# DO NOT Edit Variables Below, Unless You Know What You Are Doing
# 
# 
for IP in ${WORKER_INTERN_IP_LIST[@]}
do
export WORKER_ADDR_LIST="${IP},${WORKER_ADDR_LIST}"
done

for i in ${!CONTROLLER_LIST[@]}
do
CONTROLLER=${CONTROLLER_LIST[${i}]}
INTERN_IP=${CONTROLLER_INTERN_IP_LIST[${i}]}
URL="https://${INTERN_IP}:${KUBE_ETCD_LISTEN_CLIENT_PORT}"
export ETCD_INITIAL_CLUSTERS="etcd-${CONTROLLER}=${URL},${ETCD_INITIAL_CLUSTERS}"
done

export COMP_KUBE_SERVICE_ACCOUNT=kube-service-account
export COMP_KUBE_API_SERVER=kubernetes
export COMP_KUBE_SCHEDULER=kube-scheduler
export COMP_KUBE_CTRL_MGR=kube-controller-manager
export COMP_KUBE_PROXY=kube-proxy
